macro=;
mxram 2000;
proc DNA.tnt;

hold 1000;
taxname=;
outgroup Glossophaga;

piwe=3.589;

xpiwe=;
xpiwe[0-613; /* Fgb-i7 */
xpiwe[614-1753; /* Cytb */
xpiwe[1754-2210; /* Tshb-i2 */
xpiwe(*;

xmult = replic 1000 ratchet 10 drift 10 level 7 hits 3;
bb=tbr;

score;
nel*;

quote Length; length;
quote xCost; xpiwe&cost;
quote xHomo;xpiwe&homoplasy;
quote xSize; xpiwe&size;
quote xKval; xpiwe&kvalue;
quote xScore; xpiwe&score;
quote xSteps; xpiwe&steps;

ts DNA.ctf;
save;
ts/;

quote Score; score;
quote Homo; chomo;
quote Fit; fit;

ttags=;
export -DNA.tre;

resample jak replic 100 prob 25 freq cut 45;
ttags;
export -DNA.tre;

resample sym replic 100 prob 25 freq cut 45;
ttags;
export -DNA.tre;

log DNA.txt;
svtxt;
log/;

quit;
